import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "EBM",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  return children;
}
